-- ==========================================
-- ILIKA SHADES — Database Initialization Schema
-- Run this in your Supabase SQL Editor
-- ==========================================

-- Enable UUID extension if not enabled
create extension if not exists "uuid-ossp";

-- 1. Create Categories Table
create table if not exists public.categories (
    id bigint generated by default as identity primary key,
    name text not null unique
);

-- Enable RLS for Categories
alter table public.categories enable row level security;

-- Policies for Categories
create policy "Allow public read access to categories" 
    on public.categories for select using (true);

create policy "Allow authenticated users all access on categories" 
    on public.categories for all using (auth.role() = 'authenticated');


-- 2. Create Products Table
create table public.products (
    id bigint generated by default as identity primary key,
    category_id bigint references public.categories(id) on delete cascade,
    name text not null,
    description text,
    price numeric not null check (price >= 0),
    featured boolean default false not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Products
alter table public.products enable row level security;

-- Policies for Products
create policy "Allow public read access to products" 
    on public.products for select using (true);

create policy "Allow authenticated users all access on products" 
    on public.products for all using (auth.role() = 'authenticated');


-- 3. Create Product Images Table (to support multiple images per product)
create table public.product_images (
    id bigint generated by default as identity primary key,
    product_id bigint references public.products(id) on delete cascade not null,
    image_url text not null,
    position integer default 0 not null -- For image reordering
);

-- Enable RLS for Product Images
alter table public.product_images enable row level security;

-- Policies for Product Images
create policy "Allow public read access to product images" 
    on public.product_images for select using (true);

create policy "Allow authenticated users all access on product images" 
    on public.product_images for all using (auth.role() = 'authenticated');


-- 4. Create BusinessInfo Table (Enforces single row)
create table public.business_info (
    id integer primary key default 1 check (id = 1),
    about_us text not null,
    phone text not null,
    whatsapp text not null,
    address text not null,
    map_link text not null,
    hero_banner text not null,
    hero_title text not null,
    hero_tagline text not null,
    hours_mon_sat text not null,
    hours_sun text not null,
    hours_holidays text not null
);

-- Enable RLS for BusinessInfo
alter table public.business_info enable row level security;

-- Policies for BusinessInfo
create policy "Allow public read access to business info" 
    on public.business_info for select using (true);

create policy "Allow authenticated users to update business info" 
    on public.business_info for update using (auth.role() = 'authenticated');

create policy "Allow authenticated users to insert business info" 
    on public.business_info for insert with check (auth.role() = 'authenticated');


-- 5. Seed Initial Data
-- Insert Categories
insert into public.categories (name) values
('Curtains'),
('Mattresses'),
('Pillows'),
('Carpets'),
('Blinds')
on conflict (name) do nothing;

-- Seed BusinessInfo row
insert into public.business_info (
    id, 
    about_us, 
    phone, 
    whatsapp, 
    address, 
    map_link, 
    hero_banner, 
    hero_title, 
    hero_tagline,
    hours_mon_sat,
    hours_sun,
    hours_holidays
) values (
    1,
    'Founded in 2014, ILIKA SHADES began with a simple vision — to bring world-class furnishing solutions to every home. What started as a small curtain boutique has grown into one of the city''s most trusted premium furnishing showrooms. We specialize in curating the finest curtains, mattresses, pillows, carpets, and blinds from renowned manufacturers across the globe. Every product in our showroom is handpicked for its quality, design, and durability.',
    '+91 98765 43210',
    '+91 98765 43210',
    'ILIKA SHADES, 123 Furnishing Lane, City Center, Near Main Market, Cityname - 110001',
    'https://maps.google.com/?q=ILIKA+SHADES+City+Center',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuByTwilEA0ISVwjm_oBlGSE2K8xOB8OFY2p8iblzARzjvANhri_E4G9dV1sNCYLA63z7iUgEKdxsF59NtiyLTVwoIUvRlLkmr2riYJziCEWJac4wIPq7koFVZazfCx17sCUJjdzgImCdmxEeLeyPski7GKDDziTQdGIhvAg9tD3h-MlExJfcTIfYmEunmcRGNKgC_-g17Ab6REwKuH-CsXjwCkcToVChCiU2_rereGbL-d8a0Gj7Mfuqre9lHv-yprllfwnd70TdjtE',
    'ILIKA SHADES',
    'Luxury for Every Room',
    '10:00 AM - 8:00 PM',
    '11:00 AM - 6:00 PM',
    'By Appointment Only'
) on conflict (id) do nothing;

-- Seed Initial Products (fetching category IDs dynamically)
do $$
declare
    cat_curtains bigint;
    cat_mattresses bigint;
    cat_pillows bigint;
    cat_carpets bigint;
    cat_blinds bigint;
    prod_id bigint;
begin
    select id into cat_curtains from public.categories where name = 'Curtains';
    select id into cat_mattresses from public.categories where name = 'Mattresses';
    select id into cat_pillows from public.categories where name = 'Pillows';
    select id into cat_carpets from public.categories where name = 'Carpets';
    select id into cat_blinds from public.categories where name = 'Blinds';

    -- 1. Royal Velvet Curtain
    insert into public.products (category_id, name, description, price, featured)
    values (cat_curtains, 'Royal Velvet Curtain', 'Luxurious velvet drapes in rich jewel tones, providing excellent light blocking and elegant draping.', 2499, true)
    returning id into prod_id;
    insert into public.product_images (product_id, image_url, position) values
    (prod_id, 'https://lh3.googleusercontent.com/aida-public/AB6AXuC_pnMEFvZxinx4wZ0l3EMuZbKDVVCZW4TZNFBKB1d1XOW1wv4DF48jot1kBLa6onLlT11maQu_0oQ7jKp02vdij3KnXesblk4nIy_C_knq0cSJ15sCql5J3WL40j28im2VTbvsnuKqwBkzys3mg4JxTgoZni_nR6zxxy-qdRGn5O_a7OhQB6NntZj8wsAbu7-DVrMufT5p9uqOJw6016hcm4fJdqB0pLDUpngn4riK2kYHf9bX6KhQhzvgVWoHZXNBkDO0pSQDLCyC', 0);

    -- 2. Silk Blackout Curtain
    insert into public.products (category_id, name, description, price, featured)
    values (cat_curtains, 'Silk Blackout Curtain', 'Complete darkness and temperature control with a elegant, premium silk finish.', 3199, false)
    returning id into prod_id;
    insert into public.product_images (product_id, image_url, position) values
    (prod_id, 'https://lh3.googleusercontent.com/aida-public/AB6AXuAGQOubZuXHV3AamCBsrj1nydOYo-AxtIHKKrP8A7NGJqIhF79-cKRy6Niw_0NhI8EOgmTYEwNu_7_wyRvDzBndykBPRK_HzHthvEcdKnl9MeUvM4wpNZRHn1LA9Y-yfndNBnqCYxmjVefFZfk89Akjx1TJrDuRE_CKblKTzZZNNK3RxwS96yWTbnxKlTG-DNvGo4mBdPOsQ2BbDzmI67OinRSoRgnagvanITe7qMMq4AwrTM17e8XniZNmI6TDH4FrpGlhG-sUpEr8', 0);

    -- 3. Sheer Linen Drapes
    insert into public.products (category_id, name, description, price, featured)
    values (cat_curtains, 'Sheer Linen Drapes', 'Soft natural light filtering with a beautiful, organic linen texture for breezy interiors.', 1899, false)
    returning id into prod_id;
    insert into public.product_images (product_id, image_url, position) values
    (prod_id, 'https://lh3.googleusercontent.com/aida-public/AB6AXuAgJ4nBktOpouaTr3770eWB4N3MJxPdhIkvNYKD2jZWBnAfP51NcPkvrnWBDM-d9rk4lO9zKDzJ-9PB-2ihZfayrwOM17PzQMPF-R_3NLvLom8-yAogOiuhrad04IUDQXF4TiRg9lp7z9mTronw-rzTx1945qDD3P-wuf2BjKuJIwyAMqnf827fh0pd_Sr9ffV_Wj-1jopxkNByoR30w-4DPusEVXh0qa_-M9kEHmTIHkVhmmY-rX-XHRLVMKwz9YOfx2qxx1NieSKC', 0);

    -- 4. Orthopedic Spring Mattress
    insert into public.products (category_id, name, description, price, featured)
    values (cat_mattresses, 'Orthopedic Spring Mattress', 'Doctor-recommended spinal support system featuring pocket springs and high density foam.', 12999, false)
    returning id into prod_id;
    insert into public.product_images (product_id, image_url, position) values
    (prod_id, 'https://lh3.googleusercontent.com/aida-public/AB6AXuBE0yGo8J2FS4ZL9-1cuFXo6UrQ3PxeOUeGvzVUL3FoREvgn1YCl5MMBeXT_ZbsTd7UHCJk_LQFjWhfA5_3EUZp2B-iPer4WAd6d04H676lXzQsFYXl4UY34PTbKgmH-UKO4-CO4D1g_xRGZ6wwWbXvOudLYcDaNw0GA089NKoOpj73zSq7JYLWoBqgbkNsBS8we2swbIuUdXHq90fXjqc3xcSfd74CUh2XuiBX1Tj8px7uEkdZxnsN6DdY8fq-7dQQmQ0GQcWxr4FK', 0);

    -- 5. Memory Foam Mattress
    insert into public.products (category_id, name, description, price, featured)
    values (cat_mattresses, 'Memory Foam Mattress', 'Premium body-contouring comfort technology with cooling gel infusion and zero-motion transfer.', 18499, true)
    returning id into prod_id;
    insert into public.product_images (product_id, image_url, position) values
    (prod_id, 'https://lh3.googleusercontent.com/aida-public/AB6AXuD3ZfyJecpdo1MAKFbB3NnVgIkJ-ptgrHCkN7PiCb7eqz--SouFkKMxPwpQ8osEL2JkjtKJ2iHuFMnwZcDqEzI5UnynRR-_hK-Qcmq1q0E0arW_xy5eXo4-hY-A3hguiiXAlRuc17H91ZkPHzS6fRCLcGAJseXy2cSmfoY9CPwzTggSOV3QAHE-Kie3X19LYDTL34CwgVx8wmKSDhaw3p88inO1p095eKyrfTSHK9txv6WBLgAWZ74Zn7iJdWmBvAOU7jES-ZW9H0y1', 0);

    -- 6. Natural Latex Mattress
    insert into public.products (category_id, name, description, price, featured)
    values (cat_mattresses, 'Natural Latex Mattress', '100% natural organic latex for breathable, eco-conscious, hypoallergenic luxury sleep.', 24999, false)
    returning id into prod_id;
    insert into public.product_images (product_id, image_url, position) values
    (prod_id, 'https://lh3.googleusercontent.com/aida-public/AB6AXuDfwqnLlGO8PIvLTzX4z8QmnWkkMM-oemeVKvn8zQ8I9DdNqM-Go6qV59oIENQBmB0OIReDTYmAcggY5cXITLvEdtNkckotDvj_7ojbJYBnEXhT6isYDz-RHeBW1dS0aMQDoTuV_AR3C_FI8Okjc87_aqR3Tq2Y_9CEm3a5DQNktULQTWzi_1uxtF3BWDG_BOn2TAtCI1KR0pDtSwlyuIZEZoNTx7CTOTgb2ETrtHrpKSKKI42SyNJd72hl2o8CvJznWVeNONLit_uX', 0);

    -- 7. Cloud Comfort Pillow
    insert into public.products (category_id, name, description, price, featured)
    values (cat_pillows, 'Cloud Comfort Pillow', 'Super soft microfiber filling wrapped in breathable 100% Egyptian cotton shell.', 799, false)
    returning id into prod_id;
    insert into public.product_images (product_id, image_url, position) values
    (prod_id, 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=600&q=80', 0);

    -- 8. Memory Foam Pillow
    insert into public.products (category_id, name, description, price, featured)
    values (cat_pillows, 'Memory Foam Pillow', 'Ergonomically contoured cervical support pillow, designed to relieve neck and shoulder pressure.', 1299, false)
    returning id into prod_id;
    insert into public.product_images (product_id, image_url, position) values
    (prod_id, 'https://images.unsplash.com/photo-1632128744223-99abf185038c?auto=format&fit=crop&w=600&q=80', 0);

    -- 9. Persian Weave Carpet
    insert into public.products (category_id, name, description, price, featured)
    values (cat_carpets, 'Persian Weave Carpet', 'Hand-knotted traditional Persian masterpiece with rich, timeless jewel-tone patterns.', 5499, true)
    returning id into prod_id;
    insert into public.product_images (product_id, image_url, position) values
    (prod_id, 'https://lh3.googleusercontent.com/aida-public/AB6AXuDvVehSgTjMKEohWD6wJFA1_O1wvo3WUWMjUU0BnkLReMbL7oAEMLd7YGfX5VpHnYFlgxjmvHb5LeMiPqgRiLCfGtJs_ux5b53cgH8o7o8Z5j8xjqw_PoxTpRCOGi0uVQt8ifJCMmXXSUF5zcHCSoknNbEYuNnWpj5nl3ZpztxbQldopG7cr5tssVpOw6rsxa5u7AtG8O5wB4ejcPNcZ6r08Eq_btQLpslGMtKkIvYI-UezvHV97Kcn5bfqdwD4WJaE05ufFZfdtSMU', 0);

    -- 10. Modern Geometric Rug
    insert into public.products (category_id, name, description, price, featured)
    values (cat_carpets, 'Modern Geometric Rug', 'Abstract geometric designs with thick wool-cut pile, perfect for modern living spaces.', 3799, false)
    returning id into prod_id;
    insert into public.product_images (product_id, image_url, position) values
    (prod_id, 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=600&q=80', 0);

    -- 11. Motorized Roller Blind
    insert into public.products (category_id, name, description, price, featured)
    values (cat_blinds, 'Motorized Roller Blind', 'Smart automated light control blinds with silent motor and remote control compatibility.', 4599, true)
    returning id into prod_id;
    insert into public.product_images (product_id, image_url, position) values
    (prod_id, 'https://lh3.googleusercontent.com/aida-public/AB6AXuB_e8Y43uYydGV0Bgg1dd5zhCDbbjJkz8vZPcMOhW04UtLa9i8-cJlgb5Ky07o3uH9jgcg5xLTcW4SQ1EHxyDS-BuTgqX2AnHe7Ey3kso-lTUsC9dfEo6rMX1Hl3Wjqwcx2US93GdyJEEo2pFBW5p36QXP4uILKOUQJaJBU4OfbSuVy7PPmq_0Nk25X4BhA5rTlEzHUc1I6OgpWeYCVuUIKzeJP0vITeNzPGquFDSTiGrpKT6nqUOMCNnoHFI2y5mrf1W6n-T9udYaF', 0);

    -- 12. Wooden Venetian Blind
    insert into public.products (category_id, name, description, price, featured)
    values (cat_blinds, 'Wooden Venetian Blind', 'Premium natural basswood blinds for organic warmth, privacy, and precise light direction.', 3299, false)
    returning id into prod_id;
    insert into public.product_images (product_id, image_url, position) values
    (prod_id, 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=600&q=80', 0);

end $$;

-- 6. Storage Bucket Setup (Register Bucket)
-- Note: Create the 'shades-media' bucket in your Supabase storage console directly if this fails, or use this SQL insert:
insert into storage.buckets (id, name, public) 
values ('shades-media', 'shades-media', true)
on conflict (id) do nothing;

-- Storage Policies for 'shades-media'
create policy "Allow public read access to shades-media bucket" 
    on storage.objects for select using (bucket_id = 'shades-media');

create policy "Allow authenticated users upload to shades-media bucket" 
    on storage.objects for insert with check (bucket_id = 'shades-media' and auth.role() = 'authenticated');

create policy "Allow authenticated users update in shades-media bucket" 
    on storage.objects for update using (bucket_id = 'shades-media' and auth.role() = 'authenticated');

create policy "Allow authenticated users delete from shades-media bucket" 
    on storage.objects for delete using (bucket_id = 'shades-media' and auth.role() = 'authenticated');
